name = 'fps'
sdk = '../../sdk'
workspace = '../..'
includes = ['../../sdk/src']
link = '../../sdk/src/program.ld'
target_assets = 'render_0'
prepare = 'nu/prepare.nu'
adv = 'nu/adv.nu'
specs = [ '1ka1', '1kb1', '2ka1' ]
