call local census_init > surfaces census_surfaces LUMAP_COUNT*CS_SIZE u8,used census_used CENSUS_SIZES u64,maps census_maps u64,slots CTX_CENSUS_NEXT(contexts) 4 u64,clobber a0-a7 [67:262] :on a CENSUS build, every lumel map's directory grid at each level of its material's chain and each tile side with its read word, the contexts' census slots, the directory's line on the UART, then the clamped edge's case; a directory past CENSUS_ENTRIES exits 14 with its line
call local census_edge > clobber a0-a7 [264:350] :the clamped edge's case at the load: a 3 by 3 map in the lumel arena's tail, past every map, its last column's nodes alike and the penultimate column's last node a level under, its tile at level 1 past the last node judged by census_uniform's nodes and by census_verify's lumel_sample, both verdicts on the UART and the tail zeroed again; skipped with its line when a map reaches the tail
call local census_context index u64 > context a0 addr [352:362] :a raster context by its census index, 0 hart 0's, 1 on the workers'
call local census_frame frame u64 > totals census_totals CENSUS_SIZES*CT_SIZE u8,window census_ring CENSUS_SIZES*CENSUS_WINDOW_CLASSES*CENSUS_WINDOW u64,entries census_entries CENSUS_ENTRIES u64,revision census_revision u64,stale census_stale u8,clobber a0-a7 [364:485] :the frame's census: a lighting change first, every tile's uniformity unknown again and the revision counted; then every context's block records taken into the directory at each tile side, the slots emptied for the next frame, the lines on the UART
call local census_block record s3 addr,context s2 u64,stamp s0 u64,slot s1 u64 > clobber s5-s11,a0-a7 [487:534] :one block record at every tile side; a record no lumel map or level of the directory holds counted as dropped
call local census_tiles record s3 addr,size s11 u64 > totals census_totals CT_SIZE u8,clobber a0-a7 [536:643] :the block's tiles at one side: one tile inside the grid eligible, a pixel past the depth test its request; a block across tiles straddling, each tile its walk meets sampled
call local census_request entry u64,totals addr,tx u64,ty u64 > entry census_entries 1 u64,clobber a0-a7 [645:706] :an eligible block's request for its tile: its first demand of the frame, its class's, its context's, and its sampling
 entry :the tile's index in census_entries
call local census_first_demand entry addr,totals addr,tx u64,ty u64 > entry 0(entry) u64,counts 0(totals) CT_SIZE u8,clobber a0,a2-a7 [708:808] :a tile's first demand of the frame: into its window class's count, its stamp, its contexts and classes cleared, its uniformity once a lighting revision, a uniform verdict of the nodes checked by lumel_sample and the sampler's kept, its surface's first demand
call local census_uniform tx u64,ty u64 > uniform a0 bool,clobber a4-a7 [810:891] :1 when every lumel node the tile's texel centres read holds one value, their coordinates held under the last column and row as lumel_sample holds them
 tx :in a2, ty in a3, the record in s9, the level in s6, the size in s11
call local census_verify tx u64,ty u64 > uniform a0 bool,clobber a1-a7 [893:943] :1 when lumel_sample reads one brightness at every texel centre of the tile, the macro itself over a scratch command bearing the surface's read word, tp restored
 tx :in a2, ty in a3, the record in s9, the level in s6, the size in s11
call local census_context_surface totals addr [945:978] :the context's distinct request of the frame, counted on its surface, the surface listed at its first
 totals :in a1, the context in s2, the surface in s5, the size in s11
call local census_working frame u64,size u64,frames u64,first u64,end u64 > tiles a0 u64 [980:1009] :the distinct tiles demanded over that many frames to this one in the window classes from first to the one before end
 first :a CENSUS_WINDOW_* class, end the class past the last
call local census_spans cursor addr,first u64,end u64 > cursor a0 addr,clobber a1-a4 [1011:1052] :the working sets over 1, CENSUS_SHORT, and CENSUS_WINDOW frames in the window classes from first to the one before end, appended at the cursor
 first :in a2, end in a3, the frame in s0, the size in s1
call local census_print frame u64 > clobber a0-a7 [1054:1286] :the frame's census lines on the UART: the blocks, the lighting's revision, and the chunk in force, then for each tile side its totals and its working sets by window class, and each context's requests and its surfaces with their distinct tiles, a line in chunks of at most the chunk's bytes
call local census_head cursor addr > cursor a0 addr,clobber a1 [1288:1303] :a context line's head at the cursor, its side and its context
 cursor :in a0, the size in s1, the context in s3
call local census_line_end cursor addr > clobber a0,a7 [1305:1310] :ends the census line at the cursor and prints it
