macro tile_wrote address reg,count reg > writes tile_writes u64 [3:10] :a debug build's count of a tag or an entry written, both operands its scratch; nothing on a release build
macro tile_edge dst reg,column reg > edge dst u64,scratch t4-t6 [12:23] :a lumel cell's edge on the row in hand, the column's node above (s9) and below (s10) weighted by the row's fraction (s11), packed
call local tiles_init > surfaces tile_surfaces LUMAP_COUNT*TS_SIZE u8,free tile_free TILE_SLOTS u32,admission CTX_TILE_ADMIT(context) addr,touched CTX_TILE_TOUCHED(context) addr,memory tile_memory u64,fixed tile_fixed u64,clobber a0-a4,a7 [25:246] :the tile pool at load: every surface with a lumel map and a texture given a grid a level of its chain, the census's sizing at one side, one past sixteen bits a side or the directory's entries left uncached and counted; every slot free; each raster context its admission block; every merged chain none and the build's configuration pending; TILE_MEMORY and the tables' bytes in use read, and on a debug build printed
 context :every raster context, hart 0's and each worker's
call local tile_context index u64 > context a0 addr [248:257] :the raster context of an index, 0 hart 0's and n the worker n - 1's
call local tiles_forget > tags tile_tags TILE_SLOTS u32,entries tile_directory TILE_DIRECTORY_ENTRIES u32,free tile_free TILE_SLOTS u32,resets STAT_TILE_RESETS(stats) u64,clobber a0-a5 [260:321] :every tile forgotten, the console's L at the boundary: a READY slot's entry cleared where it names the slot, every generation advanced and every slot free, the free stack rebuilt over the effective slots, nothing in construction
call local tile_boundary > ticks STAT_TILE_TICKS(stats) u64,build STAT_TILE_BUILD_TICKS(stats) u64,overrun STAT_TILE_OVERRUN(stats) u64,clobber a0-a7 [323:395] :the tile pool's one change a frame, hart 0's at world_draw's start: the configuration in force, an L's forget, the deadlines and the quota, the frame before's batch counted and merged, the touched slots folded, construction unless frozen, the requests discarded, the frame's stamp, the occupancy
call local tile_stall > unprocessed STAT_TILE_UNPROCESSED(stats) u64,clobber a0-a7 [396:410] :on a debug build, an S frame's boundary, which draws nothing: the frame before's batch counted and discarded whole, the frame's stamp taken
call local tile_stamp > stamp tile_frame u64 [412:418] :the frame's stamp, its number plus one, its requests' under it
call local tile_configure > flags tile_flags u64,guarantee tile_guarantee u64,ring tile_ring u64,record tile_config_record REPORT_SIZE u8,clobber a0-a1,a7 [420:473] :the console's pending configuration put in force when it changed, and the configuration record sent over the API ahead of the frame it names
call local tile_batch > source tile_batch_frame u64,admitted tile_batch_admitted u64,ring tile_batch_ring u64,surfaces tile_batch_surfaces u64,union tile_requesting LUMAP_COUNT/8 u8,clobber a0-a2 [475:552] :the frame before's batch from the contexts' own counts: its source frame, its admitted requests, its greatest ring, and the union of its requesting surfaces; the merge's processed count zeroed
call local tile_merge > merged STAT_TILE_MERGED(stats) u64,unprocessed STAT_TILE_UNPROCESSED(stats) u64,clobber a0-a3 [554:711] :the batch's guaranteed tiers by requesting surface from the merge cursor, then its rings from the context cursor, each key through tile_merge_key, stopping at the merge's share or the list's end with the cursor left there, else each cursor moved on one
call local tile_merge_key key u32,surface u32 > stop a0 u64,clobber a2-a3 [713:772] :a key merged once a boundary onto its surface's chain, the surface into the merge's order at its first key; a duplicate counted processed; 1 when the list is full
call local tile_fold > references SLOT_REFERENCE(tile_slots) u8,clobber a0-a1 [774:819] :every context's touched-slot bitmap folded into the slots' reference bits and cleared
call local tile_construct > clobber a0-a7 [821:915] :the tile in construction finished first, then the merged keys a surface a pass in rotation from the build cursor, until they run out, the budget is spent, or no slot can be taken
call local tile_spent > spent a0 u64 [917:929] :1 when the quota is spent or the allowance's end has passed
call local tile_make key u32,surface u32 > stop a0 u64,clobber a1-a7 [931:1049] :a merged key's tile: built already, passed; else a slot from the free stack or CLOCK, the tile's level, column, and row from its grid, the slot BUILDING and its rows built, published when whole; 1 when the budget is spent or no slot can be taken
call local tile_evict > slot a0 i64,hand tile_hand u64 [1051:1100] :CLOCK's victim among the effective slots, two sweeps at most, retired; -1 for none
call local tile_retire slot u64 > tag 0(tile_tags) u32,entry 0(tile_directory) u32,used tile_used u64,evicted STAT_TILE_EVICTED(stats) u64 [1102:1138] :the slot's entry cleared where it names the slot under its generation, then the generation advanced and the slot FREE
call local tile_publish slot u64 > tag 0(tile_tags) u32,entry 0(tile_directory) u32,built STAT_TILES_BUILT(stats) u64 [1140:1170] :the slot READY, then its entry naming it under its generation, with the pass's mark and its reference bit clear
call local tile_discard > clobber a0-a1 [1172:1237] :the requests the boundary did not serve forgotten: the merge bitmap over the merged keys, the merged chains, the union, and every context's list and ring
call local tile_occupancy > peak tile_peak u64,memory tile_memory_peak u64 [1239:1256] :the pool's bytes in use and its memory in use, each high-water raised
call local tile_request key u32,surface u32 > admitted CTX_TILE_ADMITTED(tp) u64,dropped CTX_TILE_DROPPED(tp) u64,filtered CTX_TILE_FILTERED(tp) u64,clobber a2-a7 [1258:1338] :a missed block's tile asked of the next boundary on the block's context: the repeat filter, the surface's tier, else the open ring, else dropped
call local tile_check [1339:1351] :on a debug build, the pool's writes since world_draw's snapshot after the boundary: none, else exit 15 with its line
call local tile_build slot u64 > whole a0 u64,tile 0(tile_pool) u32,row SLOT_ROW(tile_slots) u16,quota tile_quota_left i64,clobber a1-a7 [1352:1618] :a slot's tile built a row at a time from its next row, each texel the chain's at the tile's level lit at its centre and scaled as the lit loop scales one, until whole or the quota or the allowance is spent; 1 when whole
call local alphas_measure > scales material_alpha MAX_MATERIALS*MIP_LEVELS u32,clobber a0-a5,a7 [1620:1840] :every material's alpha coverage at every level of its chain, the map's and the engine's images', and the scale that holds it, a chain with no level past 0 keeping one; a line a material under full coverage on a debug build, every level on it
call local alpha_hist_clear > counts alpha_hist 256 u64 [1842:1850] :the counts of each alpha value emptied
call local alpha_hist_pass > count a0 u64 [1852:1863] :the count of alphas at or above the pass in the histogram
call local alpha_shrink width u32,height u32,plane addr,source s10 addr,stride s11 u64 > alphas 0(plane) u8,counts alpha_hist 256 u64,clobber a3-a5 [1865:1913] :a level's alphas from the level before, each the mean of the two by two under it, into the plane, and the histogram of the plane's values
 width :the level's width, with height its height
 source :the level before's first alpha
 stride :the bytes between its alphas
call local alpha_search texels u64,whole s8 u64,target s9 u64 > threshold a0 u64,count a1 u64,clobber a2-a5 [1915:1958] :the threshold whose share of the level's alphas at or above it lies nearest the texture's target share, over the histogram, from 256, which passes nothing, down to 1; the least error in share wins, a tie the lower share, equal shares the threshold nearest the pass
 texels :the level's texels
 whole :the texture's texels
 target :the texture's count at or above the pass
 count :the count at or above the threshold
call local lumels_bright > lumels lumel_arena LUMEL_ARENA_BYTES u8 [1960:1988] :every lumel of every map set to the full brightness, one on each lane in a lumel's 256ths, for a debug build's console
call local lumels_parity > lumels lumel_arena LUMEL_ARENA_BYTES u8,clobber a0-a3 [1989:2033] :every lumel of every map set by its node's parity, a quarter on each lane where its column and row sum even and one where odd, for a debug build's console alone
