call local workers_start > started workers_started u32,active workers_active u32,grain band_grain u32,harts worker_hart WORKERS_MAX u64,clobber a0-a7 [7:99] :the raster's workers started on the lowest online secondaries, WORKERS_MAX at most, each asleep on its mailbox; the console's workers set to every worker started and the grain to GRAIN_DEFAULT; a debug build's workers line, and a line for a start refused
call local round_run > screen JAB_DISPLAY_BASE u32,depth zbuf SCREEN_W*SCREEN_H u32,stats stats 34 u64,record round ROUND_SIZE u8,claims round_next u32,context tp addr,clobber a0-a7 [101:317] :the packet in hand rendered by the frame's workers in one round: the record written, a job published a worker, one wake, every mailbox joined in order, each worker's counts, times, and bands into the frame's stats, a round a job of was cancelled finished on hart 0 and counted; no round for a packet without spans past the frame's first; on a debug build the J frame's hold and fault through the record and its cancel after the wake, and an exit 13 when a job's completion is not its generation or the bands rendered are not the round's
 context :the last worker's context, or hart 0's after a cancel
j local raster_worker mailbox addr,hart u64 [319:398] :a worker's entry, never returning: its context into tp by its mailbox's place, then each round's job awaited, its bands rendered, its own by its index or claimed from round_next, its times and bands into its mailbox's own words, the job completed and hart 0 woken; a stop exits the worker
 mailbox :its own of mailboxes, the start's argument
call local round_finish > bands a0 u64,screen JAB_DISPLAY_BASE u32,depth zbuf SCREEN_W*SCREEN_H u32,counters CTX_SPANS(raster_context) 7 u64,claims round_next u32,context tp addr,clobber a1-a7 [400:466] :a cancelled round's bands its jobs left rendered on hart 0's context, a band a worker's whose job holds none or the bands no worker claimed, its counts into the frame's stats
 bands :the bands it rendered
 context :raster_context
call local job_delay worker u64 [467:482] :on a debug build, the J frame's hold spun on rdtime when the worker is the one held
 worker :the worker's index
